/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/rlinf/rlark/api/kubeclients/clientset/versioned/typed/rlark.io/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeRlinfV1alpha1 struct {
	*testing.Fake
}

func (c *FakeRlinfV1alpha1) Addons(namespace string) v1alpha1.AddonInterface {
	return newFakeAddons(c, namespace)
}

func (c *FakeRlinfV1alpha1) Domains() v1alpha1.DomainInterface {
	return newFakeDomains(c)
}

func (c *FakeRlinfV1alpha1) DomainPeers(namespace string) v1alpha1.DomainPeerInterface {
	return newFakeDomainPeers(c, namespace)
}

func (c *FakeRlinfV1alpha1) Jobs() v1alpha1.JobInterface {
	return newFakeJobs(c)
}

func (c *FakeRlinfV1alpha1) Nodes(namespace string) v1alpha1.NodeInterface {
	return newFakeNodes(c, namespace)
}

func (c *FakeRlinfV1alpha1) Pods(namespace string) v1alpha1.PodInterface {
	return newFakePods(c, namespace)
}

func (c *FakeRlinfV1alpha1) Tasks(namespace string) v1alpha1.TaskInterface {
	return newFakeTasks(c, namespace)
}

func (c *FakeRlinfV1alpha1) Workflows() v1alpha1.WorkflowInterface {
	return newFakeWorkflows(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeRlinfV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
