/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	rlarkiov1alpha1 "github.com/rlinf/rlark/api/rlark.io/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DomainPeerLister helps list DomainPeers.
// All objects returned here must be treated as read-only.
type DomainPeerLister interface {
	// List lists all DomainPeers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rlarkiov1alpha1.DomainPeer, err error)
	// DomainPeers returns an object that can list and get DomainPeers.
	DomainPeers(namespace string) DomainPeerNamespaceLister
	DomainPeerListerExpansion
}

// domainPeerLister implements the DomainPeerLister interface.
type domainPeerLister struct {
	listers.ResourceIndexer[*rlarkiov1alpha1.DomainPeer]
}

// NewDomainPeerLister returns a new DomainPeerLister.
func NewDomainPeerLister(indexer cache.Indexer) DomainPeerLister {
	return &domainPeerLister{listers.New[*rlarkiov1alpha1.DomainPeer](indexer, rlarkiov1alpha1.Resource("domainpeer"))}
}

// DomainPeers returns an object that can list and get DomainPeers.
func (s *domainPeerLister) DomainPeers(namespace string) DomainPeerNamespaceLister {
	return domainPeerNamespaceLister{listers.NewNamespaced[*rlarkiov1alpha1.DomainPeer](s.ResourceIndexer, namespace)}
}

// DomainPeerNamespaceLister helps list and get DomainPeers.
// All objects returned here must be treated as read-only.
type DomainPeerNamespaceLister interface {
	// List lists all DomainPeers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rlarkiov1alpha1.DomainPeer, err error)
	// Get retrieves the DomainPeer from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*rlarkiov1alpha1.DomainPeer, error)
	DomainPeerNamespaceListerExpansion
}

// domainPeerNamespaceLister implements the DomainPeerNamespaceLister
// interface.
type domainPeerNamespaceLister struct {
	listers.ResourceIndexer[*rlarkiov1alpha1.DomainPeer]
}
