/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RawTaskSpecApplyConfiguration represents a declarative configuration of the RawTaskSpec type for use
// with apply.
type RawTaskSpecApplyConfiguration struct {
	Artifact    *string                    `json:"artifact,omitempty"`
	Entrypoint  []string                   `json:"entrypoint,omitempty"`
	Environment []EnvVarApplyConfiguration `json:"environment,omitempty"`
}

// RawTaskSpecApplyConfiguration constructs a declarative configuration of the RawTaskSpec type for use with
// apply.
func RawTaskSpec() *RawTaskSpecApplyConfiguration {
	return &RawTaskSpecApplyConfiguration{}
}

// WithArtifact sets the Artifact field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Artifact field is set to the value of the last call.
func (b *RawTaskSpecApplyConfiguration) WithArtifact(value string) *RawTaskSpecApplyConfiguration {
	b.Artifact = &value
	return b
}

// WithEntrypoint adds the given value to the Entrypoint field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Entrypoint field.
func (b *RawTaskSpecApplyConfiguration) WithEntrypoint(values ...string) *RawTaskSpecApplyConfiguration {
	for i := range values {
		b.Entrypoint = append(b.Entrypoint, values[i])
	}
	return b
}

// WithEnvironment adds the given value to the Environment field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Environment field.
func (b *RawTaskSpecApplyConfiguration) WithEnvironment(values ...*EnvVarApplyConfiguration) *RawTaskSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnvironment")
		}
		b.Environment = append(b.Environment, *values[i])
	}
	return b
}
