apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-backend
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: fluent-bit
    {{- range $k, $v := .AddonLabels }}
    {{ $k }}: "{{ $v }}"
    {{- end }}
type: Opaque
stringData:
  {{- if eq .Values.backend "sls" }}
  # SLS Kafka SASL password: "<AccessKeyId>#<AccessKeySecret>"
  SLS_KAFKA_PASSWORD: "{{ .Values.accessKeyId }}#{{ .Values.accessKeySecret }}"
  {{- end }}