/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AddonListerExpansion allows custom methods to be added to
// AddonLister.
type AddonListerExpansion interface{}

// AddonNamespaceListerExpansion allows custom methods to be added to
// AddonNamespaceLister.
type AddonNamespaceListerExpansion interface{}

// DomainListerExpansion allows custom methods to be added to
// DomainLister.
type DomainListerExpansion interface{}

// DomainPeerListerExpansion allows custom methods to be added to
// DomainPeerLister.
type DomainPeerListerExpansion interface{}

// DomainPeerNamespaceListerExpansion allows custom methods to be added to
// DomainPeerNamespaceLister.
type DomainPeerNamespaceListerExpansion interface{}

// JobListerExpansion allows custom methods to be added to
// JobLister.
type JobListerExpansion interface{}

// NodeListerExpansion allows custom methods to be added to
// NodeLister.
type NodeListerExpansion interface{}

// NodeNamespaceListerExpansion allows custom methods to be added to
// NodeNamespaceLister.
type NodeNamespaceListerExpansion interface{}

// PodListerExpansion allows custom methods to be added to
// PodLister.
type PodListerExpansion interface{}

// PodNamespaceListerExpansion allows custom methods to be added to
// PodNamespaceLister.
type PodNamespaceListerExpansion interface{}

// TaskListerExpansion allows custom methods to be added to
// TaskLister.
type TaskListerExpansion interface{}

// TaskNamespaceListerExpansion allows custom methods to be added to
// TaskNamespaceLister.
type TaskNamespaceListerExpansion interface{}

// WorkflowListerExpansion allows custom methods to be added to
// WorkflowLister.
type WorkflowListerExpansion interface{}
