# 数据面部署示例
# rlarkadm deploy --deploy-conf deploy-data-plane.yaml

apiVersion: rlark.io/v1alpha1
kind: DeployConfig
plane: data
control-plane-address: https://192.168.1.10:8080

cert:
  ca-cert: /etc/rlark/certs/ca.crt
  ca-key: /etc/rlark/certs/ca.key

# --- 三选一 ---

kubernetes:
  kubeconfig: /root/.kube/config
  agent-image: harbor.infini-ai.com/rlark/rlark-agent:latest

#docker:
#  agent-image: harbor.infini-ai.com/rlark/rlark-agent:latest

#raw:
#  agent-artifact: https://github.com/rlinf/rlark/releases/download/v0.1.0/rlark-agent