# 数据面部署示例
# rlarkadm deploy --deploy-conf deploy-data-plane.yaml

apiVersion: rlark.io/v1alpha1
kind: DeployConfig
plane: data
control-plane-address: https://rlark-server.rlark-system.svc:8443

cert:
  ca-cert: /Users/ar/test/rlark-deploy/ca.crt
  agent-cert: /Users/ar/test/rlark-deploy/agent.crt
  agent-key: /Users/ar/test/rlark-deploy/agent.key

# --- 三选一 ---

kubernetes:
  kubeconfig: /Users/ar/test/kubeconfig.yaml # 往 k8s 集群部署平台，访问集群的 kubeconfig
  agent-image: harbor.infini-ai.com/artest/rlark-agent:v0.0.5

#docker:
#  agent-image: harbor.infini-ai.com/share/rlark-agent:latest

#raw:
#  agent-artifact: https://github.com/rlinf/rlark/releases/download/v0.1.0/rlark-agent