/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DockerContainerSpecApplyConfiguration represents a declarative configuration of the DockerContainerSpec type for use
// with apply.
type DockerContainerSpecApplyConfiguration struct {
	Name        *string                             `json:"name,omitempty"`
	Image       *string                             `json:"image,omitempty"`
	Command     []string                            `json:"command,omitempty"`
	Args        []string                            `json:"args,omitempty"`
	Environment []EnvVarApplyConfiguration          `json:"environment,omitempty"`
	Volumes     []DockerVolumeRefApplyConfiguration `json:"volumes,omitempty"`
}

// DockerContainerSpecApplyConfiguration constructs a declarative configuration of the DockerContainerSpec type for use with
// apply.
func DockerContainerSpec() *DockerContainerSpecApplyConfiguration {
	return &DockerContainerSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DockerContainerSpecApplyConfiguration) WithName(value string) *DockerContainerSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *DockerContainerSpecApplyConfiguration) WithImage(value string) *DockerContainerSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *DockerContainerSpecApplyConfiguration) WithCommand(values ...string) *DockerContainerSpecApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}

// WithArgs adds the given value to the Args field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Args field.
func (b *DockerContainerSpecApplyConfiguration) WithArgs(values ...string) *DockerContainerSpecApplyConfiguration {
	for i := range values {
		b.Args = append(b.Args, values[i])
	}
	return b
}

// WithEnvironment adds the given value to the Environment field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Environment field.
func (b *DockerContainerSpecApplyConfiguration) WithEnvironment(values ...*EnvVarApplyConfiguration) *DockerContainerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnvironment")
		}
		b.Environment = append(b.Environment, *values[i])
	}
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *DockerContainerSpecApplyConfiguration) WithVolumes(values ...*DockerVolumeRefApplyConfiguration) *DockerContainerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumes")
		}
		b.Volumes = append(b.Volumes, *values[i])
	}
	return b
}
