/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// JobSpecApplyConfiguration represents a declarative configuration of the JobSpec type for use
// with apply.
type JobSpecApplyConfiguration struct {
	Domain       *string                             `json:"domain,omitempty"`
	Stopped      *bool                               `json:"stopped,omitempty"`
	Tasks        []JobTaskTemplateApplyConfiguration `json:"tasks,omitempty"`
	SSHPublicKey *string                             `json:"sshPublicKey,omitempty"`
}

// JobSpecApplyConfiguration constructs a declarative configuration of the JobSpec type for use with
// apply.
func JobSpec() *JobSpecApplyConfiguration {
	return &JobSpecApplyConfiguration{}
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *JobSpecApplyConfiguration) WithDomain(value string) *JobSpecApplyConfiguration {
	b.Domain = &value
	return b
}

// WithStopped sets the Stopped field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Stopped field is set to the value of the last call.
func (b *JobSpecApplyConfiguration) WithStopped(value bool) *JobSpecApplyConfiguration {
	b.Stopped = &value
	return b
}

// WithTasks adds the given value to the Tasks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tasks field.
func (b *JobSpecApplyConfiguration) WithTasks(values ...*JobTaskTemplateApplyConfiguration) *JobSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTasks")
		}
		b.Tasks = append(b.Tasks, *values[i])
	}
	return b
}

// WithSSHPublicKey sets the SSHPublicKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSHPublicKey field is set to the value of the last call.
func (b *JobSpecApplyConfiguration) WithSSHPublicKey(value string) *JobSpecApplyConfiguration {
	b.SSHPublicKey = &value
	return b
}
