/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	rlarkiov1alpha1 "github.com/rlinf/rlark/api/rlark.io/v1alpha1"
)

// JobTaskTemplateApplyConfiguration represents a declarative configuration of the JobTaskTemplate type for use
// with apply.
type JobTaskTemplateApplyConfiguration struct {
	Name                       *string `json:"name,omitempty"`
	Head                       *bool   `json:"head,omitempty"`
	TaskSpecApplyConfiguration `json:",inline"`
}

// JobTaskTemplateApplyConfiguration constructs a declarative configuration of the JobTaskTemplate type for use with
// apply.
func JobTaskTemplate() *JobTaskTemplateApplyConfiguration {
	return &JobTaskTemplateApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithName(value string) *JobTaskTemplateApplyConfiguration {
	b.Name = &value
	return b
}

// WithHead sets the Head field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Head field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithHead(value bool) *JobTaskTemplateApplyConfiguration {
	b.Head = &value
	return b
}

// WithAgentType sets the AgentType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AgentType field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithAgentType(value rlarkiov1alpha1.AgentType) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.AgentType = &value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithRole(value rlarkiov1alpha1.TaskRole) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.Role = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithDomain(value string) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.Domain = &value
	return b
}

// WithDownstreamName sets the DownstreamName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DownstreamName field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithDownstreamName(value string) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.DownstreamName = &value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *JobTaskTemplateApplyConfiguration) WithNodeSelector(entries map[string]string) *JobTaskTemplateApplyConfiguration {
	if b.TaskSpecApplyConfiguration.NodeSelector == nil && len(entries) > 0 {
		b.TaskSpecApplyConfiguration.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.TaskSpecApplyConfiguration.NodeSelector[k] = v
	}
	return b
}

// WithKubernetes sets the Kubernetes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kubernetes field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithKubernetes(value *KubernetesTaskSpecApplyConfiguration) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.Kubernetes = value
	return b
}

// WithDocker sets the Docker field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Docker field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithDocker(value *DockerTaskSpecApplyConfiguration) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.Docker = value
	return b
}

// WithRaw sets the Raw field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Raw field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithRaw(value *RawTaskSpecApplyConfiguration) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.Raw = value
	return b
}

// WithTensorBoardDir sets the TensorBoardDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TensorBoardDir field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithTensorBoardDir(value string) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.TensorBoardDir = &value
	return b
}

// WithPrepareScript sets the PrepareScript field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrepareScript field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithPrepareScript(value string) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.PrepareScript = &value
	return b
}

// WithRunScript sets the RunScript field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RunScript field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithRunScript(value string) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.RunScript = &value
	return b
}

// WithSSHPublicKey sets the SSHPublicKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSHPublicKey field is set to the value of the last call.
func (b *JobTaskTemplateApplyConfiguration) WithSSHPublicKey(value string) *JobTaskTemplateApplyConfiguration {
	b.TaskSpecApplyConfiguration.SSHPublicKey = &value
	return b
}
