/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// JobTagApplyConfiguration represents a declarative configuration of the JobTag type for use
// with apply.
//
// JobTag 表示一个任务标签，由 key 和多个 value 组成。
// key 和每个 value 长度均不超过 10 个字符；一个任务最多 10 个标签；
// 每个标签最多包含 10 个不同的 value。
type JobTagApplyConfiguration struct {
	Key    *string  `json:"key,omitempty"`
	Values []string `json:"values,omitempty"`
}

// JobTagApplyConfiguration constructs a declarative configuration of the JobTag type for use with
// apply.
func JobTag() *JobTagApplyConfiguration {
	return &JobTagApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *JobTagApplyConfiguration) WithKey(value string) *JobTagApplyConfiguration {
	b.Key = &value
	return b
}

// WithValues adds the given values to the Values field in the declarative configuration
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
func (b *JobTagApplyConfiguration) WithValues(values ...string) *JobTagApplyConfiguration {
	b.Values = append(b.Values, values...)
	return b
}
