/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NodeEventApplyConfiguration represents a declarative configuration of the NodeEvent type for use
// with apply.
//
// NodeEvent represents a Kubernetes Event observed on a node that is relevant
// for surfacing to operators (e.g. DiskPressure warnings, FailedScheduling,
// image pull failures). The node-agent collects Warning events plus a small
// set of Normal scheduling/pulling events and writes them to Node.status.events.
type NodeEventApplyConfiguration struct {
	Type *string `json:"type,omitempty"`
	// Warning / Normal
	Reason *string `json:"reason,omitempty"`
	// DiskPressure, FailedScheduling, Pulling, etc.
	Message  *string  `json:"message,omitempty"`
	LastTime *v1.Time `json:"lastTime,omitempty"`
	// 最近一次发生时间
	Count  *int32  `json:"count,omitempty"`
	Source *string `json:"source,omitempty"`
	// 事件来源组件，如 kubelet
	ObjectKind *string `json:"objectKind,omitempty"`
	// 涉及对象类型：Node / Pod
	ObjectName *string `json:"objectName,omitempty"`
}

// NodeEventApplyConfiguration constructs a declarative configuration of the NodeEvent type for use with
// apply.
func NodeEvent() *NodeEventApplyConfiguration {
	return &NodeEventApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *NodeEventApplyConfiguration) WithType(value string) *NodeEventApplyConfiguration {
	b.Type = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *NodeEventApplyConfiguration) WithReason(value string) *NodeEventApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *NodeEventApplyConfiguration) WithMessage(value string) *NodeEventApplyConfiguration {
	b.Message = &value
	return b
}

// WithLastTime sets the LastTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTime field is set to the value of the last call.
func (b *NodeEventApplyConfiguration) WithLastTime(value v1.Time) *NodeEventApplyConfiguration {
	b.LastTime = &value
	return b
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *NodeEventApplyConfiguration) WithCount(value int32) *NodeEventApplyConfiguration {
	b.Count = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *NodeEventApplyConfiguration) WithSource(value string) *NodeEventApplyConfiguration {
	b.Source = &value
	return b
}

// WithObjectKind sets the ObjectKind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectKind field is set to the value of the last call.
func (b *NodeEventApplyConfiguration) WithObjectKind(value string) *NodeEventApplyConfiguration {
	b.ObjectKind = &value
	return b
}

// WithObjectName sets the ObjectName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectName field is set to the value of the last call.
func (b *NodeEventApplyConfiguration) WithObjectName(value string) *NodeEventApplyConfiguration {
	b.ObjectName = &value
	return b
}
