/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NodeInfoApplyConfiguration represents a declarative configuration of the NodeInfo type for use
// with apply.
type NodeInfoApplyConfiguration struct {
	Architecture    *string `json:"architecture,omitempty"`
	KernelVersion   *string `json:"kernelVersion,omitempty"`
	AgentVersion    *string `json:"agentVersion,omitempty"`
	OperatingSystem *string `json:"operatingSystem,omitempty"`
}

// NodeInfoApplyConfiguration constructs a declarative configuration of the NodeInfo type for use with
// apply.
func NodeInfo() *NodeInfoApplyConfiguration {
	return &NodeInfoApplyConfiguration{}
}

// WithArchitecture sets the Architecture field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Architecture field is set to the value of the last call.
func (b *NodeInfoApplyConfiguration) WithArchitecture(value string) *NodeInfoApplyConfiguration {
	b.Architecture = &value
	return b
}

// WithKernelVersion sets the KernelVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KernelVersion field is set to the value of the last call.
func (b *NodeInfoApplyConfiguration) WithKernelVersion(value string) *NodeInfoApplyConfiguration {
	b.KernelVersion = &value
	return b
}

// WithAgentVersion sets the AgentVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AgentVersion field is set to the value of the last call.
func (b *NodeInfoApplyConfiguration) WithAgentVersion(value string) *NodeInfoApplyConfiguration {
	b.AgentVersion = &value
	return b
}

// WithOperatingSystem sets the OperatingSystem field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperatingSystem field is set to the value of the last call.
func (b *NodeInfoApplyConfiguration) WithOperatingSystem(value string) *NodeInfoApplyConfiguration {
	b.OperatingSystem = &value
	return b
}
