/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PodSpecApplyConfiguration represents a declarative configuration of the PodSpec type for use
// with apply.
//
// PodSpec 包含 Pod 的标识和引用信息，由数据面上报时设置。
type PodSpecApplyConfiguration struct {
	Domain *string `json:"domain,omitempty"`
	// 所属 Domain 名称
	TaskNamespace *string `json:"taskNamespace,omitempty"`
	// 关联的 Task 命名空间
	TaskName *string `json:"taskName,omitempty"`
	// 关联的 Task 名称
	PodNamespace *string `json:"podNamespace,omitempty"`
	// 数据面 Pod 所在的命名空间
	PodName *string `json:"podName,omitempty"`
}

// PodSpecApplyConfiguration constructs a declarative configuration of the PodSpec type for use with
// apply.
func PodSpec() *PodSpecApplyConfiguration {
	return &PodSpecApplyConfiguration{}
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *PodSpecApplyConfiguration) WithDomain(value string) *PodSpecApplyConfiguration {
	b.Domain = &value
	return b
}

// WithTaskNamespace sets the TaskNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TaskNamespace field is set to the value of the last call.
func (b *PodSpecApplyConfiguration) WithTaskNamespace(value string) *PodSpecApplyConfiguration {
	b.TaskNamespace = &value
	return b
}

// WithTaskName sets the TaskName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TaskName field is set to the value of the last call.
func (b *PodSpecApplyConfiguration) WithTaskName(value string) *PodSpecApplyConfiguration {
	b.TaskName = &value
	return b
}

// WithPodNamespace sets the PodNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodNamespace field is set to the value of the last call.
func (b *PodSpecApplyConfiguration) WithPodNamespace(value string) *PodSpecApplyConfiguration {
	b.PodNamespace = &value
	return b
}

// WithPodName sets the PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodName field is set to the value of the last call.
func (b *PodSpecApplyConfiguration) WithPodName(value string) *PodSpecApplyConfiguration {
	b.PodName = &value
	return b
}
