/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PullProgressApplyConfiguration represents a declarative configuration of the PullProgress type for use
// with apply.
type PullProgressApplyConfiguration struct {
	Image      *string  `json:"image"`
	Downloaded *int64   `json:"downloaded"`
	Total      *int64   `json:"total"`
	Speed      *float64 `json:"speed"`
	Status     *string  `json:"status"`
	Message    *string  `json:"message,omitempty"`
}

// PullProgressApplyConfiguration constructs a declarative configuration of the PullProgress type for use with
// apply.
func PullProgress() *PullProgressApplyConfiguration {
	return &PullProgressApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *PullProgressApplyConfiguration) WithImage(value string) *PullProgressApplyConfiguration {
	b.Image = &value
	return b
}

// WithDownloaded sets the Downloaded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Downloaded field is set to the value of the last call.
func (b *PullProgressApplyConfiguration) WithDownloaded(value int64) *PullProgressApplyConfiguration {
	b.Downloaded = &value
	return b
}

// WithTotal sets the Total field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Total field is set to the value of the last call.
func (b *PullProgressApplyConfiguration) WithTotal(value int64) *PullProgressApplyConfiguration {
	b.Total = &value
	return b
}

// WithSpeed sets the Speed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Speed field is set to the value of the last call.
func (b *PullProgressApplyConfiguration) WithSpeed(value float64) *PullProgressApplyConfiguration {
	b.Speed = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *PullProgressApplyConfiguration) WithStatus(value string) *PullProgressApplyConfiguration {
	b.Status = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *PullProgressApplyConfiguration) WithMessage(value string) *PullProgressApplyConfiguration {
	b.Message = &value
	return b
}
