/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	rlarkiov1alpha1 "github.com/rlinf/rlark/api/rlark.io/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TaskStatusApplyConfiguration represents a declarative configuration of the TaskStatus type for use
// with apply.
type TaskStatusApplyConfiguration struct {
	Phase            *rlarkiov1alpha1.TaskPhase       `json:"phase,omitempty"`
	ObservedNodes    []string                         `json:"observedNodes,omitempty"`
	Conditions       []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	StartTime        *metav1.Time                     `json:"startTime,omitempty"`
	CompletionTime   *metav1.Time                     `json:"completionTime,omitempty"`
	Message          *string                          `json:"message,omitempty"`
	RetryCount       *int32                           `json:"retryCount,omitempty"`
	TensorBoardProxy *string                          `json:"tensorBoardProxy,omitempty"`
}

// TaskStatusApplyConfiguration constructs a declarative configuration of the TaskStatus type for use with
// apply.
func TaskStatus() *TaskStatusApplyConfiguration {
	return &TaskStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithPhase(value rlarkiov1alpha1.TaskPhase) *TaskStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithObservedNodes adds the given value to the ObservedNodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ObservedNodes field.
func (b *TaskStatusApplyConfiguration) WithObservedNodes(values ...string) *TaskStatusApplyConfiguration {
	for i := range values {
		b.ObservedNodes = append(b.ObservedNodes, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TaskStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *TaskStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithStartTime(value metav1.Time) *TaskStatusApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithCompletionTime(value metav1.Time) *TaskStatusApplyConfiguration {
	b.CompletionTime = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithMessage(value string) *TaskStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithRetryCount sets the RetryCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryCount field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithRetryCount(value int32) *TaskStatusApplyConfiguration {
	b.RetryCount = &value
	return b
}

// WithTensorBoardProxy sets the TensorBoardProxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TensorBoardProxy field is set to the value of the last call.
func (b *TaskStatusApplyConfiguration) WithTensorBoardProxy(value string) *TaskStatusApplyConfiguration {
	b.TensorBoardProxy = &value
	return b
}
