/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	rlarkiov1alpha1 "github.com/rlinf/rlark/api/rlark.io/v1alpha1"
)

// TaskSpecApplyConfiguration represents a declarative configuration of the TaskSpec type for use
// with apply.
type TaskSpecApplyConfiguration struct {
	AgentType *rlarkiov1alpha1.AgentType `json:"agentType,omitempty"`
	Role      *rlarkiov1alpha1.TaskRole  `json:"role,omitempty"`
	Domain    *string                    `json:"domain,omitempty"`
	// 所属 Domain 名称，从 Job 继承
	DownstreamName *string           `json:"downstreamName,omitempty"`
	NodeSelector   map[string]string `json:"nodeSelector,omitempty"`
	// value 可以是 ',' 分隔的多个值
	Kubernetes     *KubernetesTaskSpecApplyConfiguration `json:"kubernetes,omitempty"`
	Docker         *DockerTaskSpecApplyConfiguration     `json:"docker,omitempty"`
	Raw            *RawTaskSpecApplyConfiguration        `json:"raw,omitempty"`
	TensorBoardDir *string                               `json:"tensorBoardDir,omitempty"`
	PrepareScript  *string                               `json:"prepareScript,omitempty"`
	// Ray 集群启动前执行的脚本
	RunScript *string `json:"runScript,omitempty"`
	// Ray 集群就绪后执行的脚本（仅 head 节点）
	SSHPublicKey *string `json:"sshPublicKey,omitempty"`
}

// TaskSpecApplyConfiguration constructs a declarative configuration of the TaskSpec type for use with
// apply.
func TaskSpec() *TaskSpecApplyConfiguration {
	return &TaskSpecApplyConfiguration{}
}

// WithAgentType sets the AgentType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AgentType field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithAgentType(value rlarkiov1alpha1.AgentType) *TaskSpecApplyConfiguration {
	b.AgentType = &value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithRole(value rlarkiov1alpha1.TaskRole) *TaskSpecApplyConfiguration {
	b.Role = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithDomain(value string) *TaskSpecApplyConfiguration {
	b.Domain = &value
	return b
}

// WithDownstreamName sets the DownstreamName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DownstreamName field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithDownstreamName(value string) *TaskSpecApplyConfiguration {
	b.DownstreamName = &value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *TaskSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *TaskSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithKubernetes sets the Kubernetes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kubernetes field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithKubernetes(value *KubernetesTaskSpecApplyConfiguration) *TaskSpecApplyConfiguration {
	b.Kubernetes = value
	return b
}

// WithDocker sets the Docker field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Docker field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithDocker(value *DockerTaskSpecApplyConfiguration) *TaskSpecApplyConfiguration {
	b.Docker = value
	return b
}

// WithRaw sets the Raw field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Raw field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithRaw(value *RawTaskSpecApplyConfiguration) *TaskSpecApplyConfiguration {
	b.Raw = value
	return b
}

// WithTensorBoardDir sets the TensorBoardDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TensorBoardDir field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithTensorBoardDir(value string) *TaskSpecApplyConfiguration {
	b.TensorBoardDir = &value
	return b
}

// WithPrepareScript sets the PrepareScript field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrepareScript field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithPrepareScript(value string) *TaskSpecApplyConfiguration {
	b.PrepareScript = &value
	return b
}

// WithRunScript sets the RunScript field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RunScript field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithRunScript(value string) *TaskSpecApplyConfiguration {
	b.RunScript = &value
	return b
}

// WithSSHPublicKey sets the SSHPublicKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSHPublicKey field is set to the value of the last call.
func (b *TaskSpecApplyConfiguration) WithSSHPublicKey(value string) *TaskSpecApplyConfiguration {
	b.SSHPublicKey = &value
	return b
}
