/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	rlarkiov1alpha1 "github.com/rlinf/rlark/api/rlark.io/v1alpha1"
)

// WorkflowJobStatusApplyConfiguration represents a declarative configuration of the WorkflowJobStatus type for use
// with apply.
type WorkflowJobStatusApplyConfiguration struct {
	Name    *string                   `json:"name,omitempty"`
	Phase   *rlarkiov1alpha1.JobPhase `json:"phase,omitempty"`
	Message *string                   `json:"message,omitempty"`
}

// WorkflowJobStatusApplyConfiguration constructs a declarative configuration of the WorkflowJobStatus type for use with
// apply.
func WorkflowJobStatus() *WorkflowJobStatusApplyConfiguration {
	return &WorkflowJobStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *WorkflowJobStatusApplyConfiguration) WithName(value string) *WorkflowJobStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *WorkflowJobStatusApplyConfiguration) WithPhase(value rlarkiov1alpha1.JobPhase) *WorkflowJobStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *WorkflowJobStatusApplyConfiguration) WithMessage(value string) *WorkflowJobStatusApplyConfiguration {
	b.Message = &value
	return b
}
