/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationrlarkiov1alpha1 "github.com/rlinf/rlark/api/kubeclients/applyconfiguration/rlark.io/v1alpha1"
	scheme "github.com/rlinf/rlark/api/kubeclients/clientset/versioned/scheme"
	rlarkiov1alpha1 "github.com/rlinf/rlark/api/rlark.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DomainPeersGetter has a method to return a DomainPeerInterface.
// A group's client should implement this interface.
type DomainPeersGetter interface {
	DomainPeers(namespace string) DomainPeerInterface
}

// DomainPeerInterface has methods to work with DomainPeer resources.
type DomainPeerInterface interface {
	Create(ctx context.Context, domainPeer *rlarkiov1alpha1.DomainPeer, opts v1.CreateOptions) (*rlarkiov1alpha1.DomainPeer, error)
	Update(ctx context.Context, domainPeer *rlarkiov1alpha1.DomainPeer, opts v1.UpdateOptions) (*rlarkiov1alpha1.DomainPeer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, domainPeer *rlarkiov1alpha1.DomainPeer, opts v1.UpdateOptions) (*rlarkiov1alpha1.DomainPeer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*rlarkiov1alpha1.DomainPeer, error)
	List(ctx context.Context, opts v1.ListOptions) (*rlarkiov1alpha1.DomainPeerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *rlarkiov1alpha1.DomainPeer, err error)
	Apply(ctx context.Context, domainPeer *applyconfigurationrlarkiov1alpha1.DomainPeerApplyConfiguration, opts v1.ApplyOptions) (result *rlarkiov1alpha1.DomainPeer, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, domainPeer *applyconfigurationrlarkiov1alpha1.DomainPeerApplyConfiguration, opts v1.ApplyOptions) (result *rlarkiov1alpha1.DomainPeer, err error)
	DomainPeerExpansion
}

// domainPeers implements DomainPeerInterface
type domainPeers struct {
	*gentype.ClientWithListAndApply[*rlarkiov1alpha1.DomainPeer, *rlarkiov1alpha1.DomainPeerList, *applyconfigurationrlarkiov1alpha1.DomainPeerApplyConfiguration]
}

// newDomainPeers returns a DomainPeers
func newDomainPeers(c *RlinfV1alpha1Client, namespace string) *domainPeers {
	return &domainPeers{
		gentype.NewClientWithListAndApply[*rlarkiov1alpha1.DomainPeer, *rlarkiov1alpha1.DomainPeerList, *applyconfigurationrlarkiov1alpha1.DomainPeerApplyConfiguration](
			"domainpeers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *rlarkiov1alpha1.DomainPeer { return &rlarkiov1alpha1.DomainPeer{} },
			func() *rlarkiov1alpha1.DomainPeerList { return &rlarkiov1alpha1.DomainPeerList{} },
		),
	}
}
