/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	scheme "github.com/rlinf/rlark/api/kubeclients/clientset/versioned/scheme"
	rlarkiov1alpha1 "github.com/rlinf/rlark/api/rlark.io/v1alpha1"
	rest "k8s.io/client-go/rest"
)

type RlinfV1alpha1Interface interface {
	RESTClient() rest.Interface
	AddonsGetter
	DomainsGetter
	DomainPeersGetter
	JobsGetter
	NodesGetter
	PodsGetter
	TasksGetter
	WorkflowsGetter
}

// RlinfV1alpha1Client is used to interact with features provided by the rlinf.io group.
type RlinfV1alpha1Client struct {
	restClient rest.Interface
}

func (c *RlinfV1alpha1Client) Addons(namespace string) AddonInterface {
	return newAddons(c, namespace)
}

func (c *RlinfV1alpha1Client) Domains() DomainInterface {
	return newDomains(c)
}

func (c *RlinfV1alpha1Client) DomainPeers(namespace string) DomainPeerInterface {
	return newDomainPeers(c, namespace)
}

func (c *RlinfV1alpha1Client) Jobs() JobInterface {
	return newJobs(c)
}

func (c *RlinfV1alpha1Client) Nodes(namespace string) NodeInterface {
	return newNodes(c, namespace)
}

func (c *RlinfV1alpha1Client) Pods(namespace string) PodInterface {
	return newPods(c, namespace)
}

func (c *RlinfV1alpha1Client) Tasks(namespace string) TaskInterface {
	return newTasks(c, namespace)
}

func (c *RlinfV1alpha1Client) Workflows() WorkflowInterface {
	return newWorkflows(c)
}

// NewForConfig creates a new RlinfV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*RlinfV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new RlinfV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*RlinfV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &RlinfV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new RlinfV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *RlinfV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new RlinfV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *RlinfV1alpha1Client {
	return &RlinfV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := rlarkiov1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *RlinfV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
