/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationrlarkiov1alpha1 "github.com/rlinf/rlark/api/kubeclients/applyconfiguration/rlark.io/v1alpha1"
	scheme "github.com/rlinf/rlark/api/kubeclients/clientset/versioned/scheme"
	rlarkiov1alpha1 "github.com/rlinf/rlark/api/rlark.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TasksGetter has a method to return a TaskInterface.
// A group's client should implement this interface.
type TasksGetter interface {
	Tasks(namespace string) TaskInterface
}

// TaskInterface has methods to work with Task resources.
type TaskInterface interface {
	Create(ctx context.Context, task *rlarkiov1alpha1.Task, opts v1.CreateOptions) (*rlarkiov1alpha1.Task, error)
	Update(ctx context.Context, task *rlarkiov1alpha1.Task, opts v1.UpdateOptions) (*rlarkiov1alpha1.Task, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, task *rlarkiov1alpha1.Task, opts v1.UpdateOptions) (*rlarkiov1alpha1.Task, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*rlarkiov1alpha1.Task, error)
	List(ctx context.Context, opts v1.ListOptions) (*rlarkiov1alpha1.TaskList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *rlarkiov1alpha1.Task, err error)
	Apply(ctx context.Context, task *applyconfigurationrlarkiov1alpha1.TaskApplyConfiguration, opts v1.ApplyOptions) (result *rlarkiov1alpha1.Task, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, task *applyconfigurationrlarkiov1alpha1.TaskApplyConfiguration, opts v1.ApplyOptions) (result *rlarkiov1alpha1.Task, err error)
	TaskExpansion
}

// tasks implements TaskInterface
type tasks struct {
	*gentype.ClientWithListAndApply[*rlarkiov1alpha1.Task, *rlarkiov1alpha1.TaskList, *applyconfigurationrlarkiov1alpha1.TaskApplyConfiguration]
}

// newTasks returns a Tasks
func newTasks(c *RlinfV1alpha1Client, namespace string) *tasks {
	return &tasks{
		gentype.NewClientWithListAndApply[*rlarkiov1alpha1.Task, *rlarkiov1alpha1.TaskList, *applyconfigurationrlarkiov1alpha1.TaskApplyConfiguration](
			"tasks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *rlarkiov1alpha1.Task { return &rlarkiov1alpha1.Task{} },
			func() *rlarkiov1alpha1.TaskList { return &rlarkiov1alpha1.TaskList{} },
		),
	}
}
