apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-driver-rclone
  namespace: rlark-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-driver-rclone
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumes", "persistentvolumeclaims", "secrets"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments", "csidrivers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-driver-rclone
subjects:
  - kind: ServiceAccount
    name: csi-driver-rclone
    namespace: rlark-system
roleRef:
  kind: ClusterRole
  name: csi-driver-rclone
  apiGroup: rbac.authorization.k8s.io