/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DomainIPAllocationApplyConfiguration represents a declarative configuration of the DomainIPAllocation type for use
// with apply.
type DomainIPAllocationApplyConfiguration struct {
	IP  *string `json:"ip,omitempty"`
	Job *string `json:"job,omitempty"`
	// job name
	Task *string `json:"task,omitempty"`
	// namespace / task name
	Pod *string `json:"pod,omitempty"`
}

// DomainIPAllocationApplyConfiguration constructs a declarative configuration of the DomainIPAllocation type for use with
// apply.
func DomainIPAllocation() *DomainIPAllocationApplyConfiguration {
	return &DomainIPAllocationApplyConfiguration{}
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *DomainIPAllocationApplyConfiguration) WithIP(value string) *DomainIPAllocationApplyConfiguration {
	b.IP = &value
	return b
}

// WithJob sets the Job field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Job field is set to the value of the last call.
func (b *DomainIPAllocationApplyConfiguration) WithJob(value string) *DomainIPAllocationApplyConfiguration {
	b.Job = &value
	return b
}

// WithTask sets the Task field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Task field is set to the value of the last call.
func (b *DomainIPAllocationApplyConfiguration) WithTask(value string) *DomainIPAllocationApplyConfiguration {
	b.Task = &value
	return b
}

// WithPod sets the Pod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pod field is set to the value of the last call.
func (b *DomainIPAllocationApplyConfiguration) WithPod(value string) *DomainIPAllocationApplyConfiguration {
	b.Pod = &value
	return b
}
