/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DomainPeerSpecApplyConfiguration represents a declarative configuration of the DomainPeerSpec type for use
// with apply.
type DomainPeerSpecApplyConfiguration struct {
	PrefixLen *int                              `json:"prefixLen,omitempty"`
	Pods      []DomainPodInfoApplyConfiguration `json:"pods,omitempty"`
	Cert      *string                           `json:"cert,omitempty"`
	Key       *string                           `json:"key,omitempty"`
}

// DomainPeerSpecApplyConfiguration constructs a declarative configuration of the DomainPeerSpec type for use with
// apply.
func DomainPeerSpec() *DomainPeerSpecApplyConfiguration {
	return &DomainPeerSpecApplyConfiguration{}
}

// WithPrefixLen sets the PrefixLen field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefixLen field is set to the value of the last call.
func (b *DomainPeerSpecApplyConfiguration) WithPrefixLen(value int) *DomainPeerSpecApplyConfiguration {
	b.PrefixLen = &value
	return b
}

// WithPods adds the given value to the Pods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pods field.
func (b *DomainPeerSpecApplyConfiguration) WithPods(values ...*DomainPodInfoApplyConfiguration) *DomainPeerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPods")
		}
		b.Pods = append(b.Pods, *values[i])
	}
	return b
}

// WithCert sets the Cert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cert field is set to the value of the last call.
func (b *DomainPeerSpecApplyConfiguration) WithCert(value string) *DomainPeerSpecApplyConfiguration {
	b.Cert = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *DomainPeerSpecApplyConfiguration) WithKey(value string) *DomainPeerSpecApplyConfiguration {
	b.Key = &value
	return b
}
