/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DomainPodInfoApplyConfiguration represents a declarative configuration of the DomainPodInfo type for use
// with apply.
type DomainPodInfoApplyConfiguration struct {
	GlobalNamespace *string `json:"globalNamespace,omitempty"`
	Namespace       *string `json:"namespace,omitempty"`
	Name            *string `json:"name,omitempty"`
	UID             *string `json:"uid,omitempty"`
	Node            *string `json:"node,omitempty"`
	IP              *string `json:"ip,omitempty"`
	LocalIP         *string `json:"localIP,omitempty"`
}

// DomainPodInfoApplyConfiguration constructs a declarative configuration of the DomainPodInfo type for use with
// apply.
func DomainPodInfo() *DomainPodInfoApplyConfiguration {
	return &DomainPodInfoApplyConfiguration{}
}

// WithGlobalNamespace sets the GlobalNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GlobalNamespace field is set to the value of the last call.
func (b *DomainPodInfoApplyConfiguration) WithGlobalNamespace(value string) *DomainPodInfoApplyConfiguration {
	b.GlobalNamespace = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *DomainPodInfoApplyConfiguration) WithNamespace(value string) *DomainPodInfoApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DomainPodInfoApplyConfiguration) WithName(value string) *DomainPodInfoApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *DomainPodInfoApplyConfiguration) WithUID(value string) *DomainPodInfoApplyConfiguration {
	b.UID = &value
	return b
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *DomainPodInfoApplyConfiguration) WithNode(value string) *DomainPodInfoApplyConfiguration {
	b.Node = &value
	return b
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *DomainPodInfoApplyConfiguration) WithIP(value string) *DomainPodInfoApplyConfiguration {
	b.IP = &value
	return b
}

// WithLocalIP sets the LocalIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalIP field is set to the value of the last call.
func (b *DomainPodInfoApplyConfiguration) WithLocalIP(value string) *DomainPodInfoApplyConfiguration {
	b.LocalIP = &value
	return b
}
