/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	rlarkiov1alpha1 "github.com/rlinf/rlark/api/rlark.io/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// KubernetesWorkloadSpecApplyConfiguration represents a declarative configuration of the KubernetesWorkloadSpec type for use
// with apply.
type KubernetesWorkloadSpecApplyConfiguration struct {
	Kind          *rlarkiov1alpha1.KubernetesWorkloadKind `json:"kind,omitempty"`
	Replicas      *int32                                  `json:"replicas,omitempty"`
	Template      *v1.PodTemplateSpec                     `json:"template,omitempty"`
	PvcStorageMap map[string]string                       `json:"pvcStorageMap,omitempty"`
}

// KubernetesWorkloadSpecApplyConfiguration constructs a declarative configuration of the KubernetesWorkloadSpec type for use with
// apply.
func KubernetesWorkloadSpec() *KubernetesWorkloadSpecApplyConfiguration {
	return &KubernetesWorkloadSpecApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *KubernetesWorkloadSpecApplyConfiguration) WithKind(value rlarkiov1alpha1.KubernetesWorkloadKind) *KubernetesWorkloadSpecApplyConfiguration {
	b.Kind = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *KubernetesWorkloadSpecApplyConfiguration) WithReplicas(value int32) *KubernetesWorkloadSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *KubernetesWorkloadSpecApplyConfiguration) WithTemplate(value v1.PodTemplateSpec) *KubernetesWorkloadSpecApplyConfiguration {
	b.Template = &value
	return b
}

// WithPvcStorageMap puts the entries into the PvcStorageMap field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PvcStorageMap field,
// overwriting an existing map entries in PvcStorageMap field with the same key.
func (b *KubernetesWorkloadSpecApplyConfiguration) WithPvcStorageMap(entries map[string]string) *KubernetesWorkloadSpecApplyConfiguration {
	if b.PvcStorageMap == nil && len(entries) > 0 {
		b.PvcStorageMap = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PvcStorageMap[k] = v
	}
	return b
}
