/*
Copyright 2024 The RLInf Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// WorkflowJobTemplateApplyConfiguration represents a declarative configuration of the WorkflowJobTemplate type for use
// with apply.
type WorkflowJobTemplateApplyConfiguration struct {
	Name         *string                    `json:"name,omitempty"`
	Dependencies []string                   `json:"dependencies,omitempty"`
	Spec         *JobSpecApplyConfiguration `json:"spec,omitempty"`
}

// WorkflowJobTemplateApplyConfiguration constructs a declarative configuration of the WorkflowJobTemplate type for use with
// apply.
func WorkflowJobTemplate() *WorkflowJobTemplateApplyConfiguration {
	return &WorkflowJobTemplateApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *WorkflowJobTemplateApplyConfiguration) WithName(value string) *WorkflowJobTemplateApplyConfiguration {
	b.Name = &value
	return b
}

// WithDependencies adds the given value to the Dependencies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Dependencies field.
func (b *WorkflowJobTemplateApplyConfiguration) WithDependencies(values ...string) *WorkflowJobTemplateApplyConfiguration {
	for i := range values {
		b.Dependencies = append(b.Dependencies, values[i])
	}
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *WorkflowJobTemplateApplyConfiguration) WithSpec(value *JobSpecApplyConfiguration) *WorkflowJobTemplateApplyConfiguration {
	b.Spec = value
	return b
}
