name: CI Test

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo "CI Test triggered successfully"