name: CI Test

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

concurrency:
  group: code-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # =============================================== check changes ====================================================
  check-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      docker_filter: ${{ steps.filter.outputs.docker_filter }}
      unit_test_filter: ${{ steps.filter.outputs.unit_test_filter }}
      lint_filter: ${{ steps.filter.outputs.lint_filter }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Detect file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            docker_filter:
              - 'apps/rlark/**/Dockerfile'
              - 'apps/rlark-ui/**/Dockerfile'
              - 'apps/embodied-runtime/**/Dockerfile'
              - 'apps/rlark/cmd/**'
              - 'apps/rlark/pkg/**'
              - 'api/**'
              - '.github/workflows/docker-build.yml'
            unit_test_filter:
              - '**/*.go'
              - '**/go.mod'
              - '**/go.sum'
              - '.github/workflows/unit-tests.yml'
            lint_filter:
              - '**/*.go'
              - 'apps/rlark-ui/**'
              - '**/go.mod'
              - '**/go.sum'
              - '.github/workflows/lint.yml'

  # =============================================== lint ====================================================
  lint:
    needs: [check-changes]
    if: needs.check-changes.outputs.lint_filter == 'true'
    uses: ./.github/workflows/lint.yml

  # =============================================== unit tests ====================================================
  unit-tests:
    needs: [check-changes]
    if: needs.check-changes.outputs.unit_test_filter == 'true'
    uses: ./.github/workflows/unit-tests.yml

  # =============================================== docker build ====================================================
  docker-build:
    needs: [check-changes]
    if: needs.check-changes.outputs.docker_filter == 'true'
    uses: ./.github/workflows/docker-build.yml

  # =============================================== finale ====================================================
  ci-test-finish:
    needs:
      [
        check-changes,
        lint,
        unit-tests,
        docker-build,
      ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check all dependent job statuses
        run: |
          json_needs='${{ toJson(needs) }}'

          job_names=$(echo "$json_needs" | jq -r 'keys_unsorted[]')

          for job in $job_names; do
            result=$(echo "$json_needs" | jq -r --arg j "$job" '.[$j].result')

            echo "$job: $result"

            if [[ "$result" == "failure" || "$result" == "cancelled" ]]; then
              echo "The above jobs failed."
              exit 1
            fi
          done

          echo "All jobs completed successfully"
          exit 0