name: Commit Check

on:
  push:
  pull_request:

jobs:
  commit-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: commit-check/commit-check-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: true
          branch: false
          author-name: false
          author-email: false
          commit-signoff: true
          merge-base: false
          imperative: false
          job-summary: true