name: Unit Tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "apps/rlark/go.mod"
          cache: true
          cache-dependency-path: "apps/rlark/go.sum"

      - name: Run rlark unit tests
        timeout-minutes: 10
        working-directory: apps/rlark
        run: go test ./pkg/... -v -count=1 -short

      - name: Run api unit tests
        timeout-minutes: 5
        working-directory: api
        run: go test ./... -v -count=1 -short